/* eslint-disable */
export const news = {
  items: [
    {
      id: 40601,
      tipo: 'Notícia',
      titulo: 'ENCE abrirá pré-inscrições para o curso Inteligência Artificial em Políticas Públicas',
      introducao: 'A Escola Nacional de Ciências Estatísticas (ENCE) abrirá pré-inscrições em 5 de julho para o curso Inteligência Artificial em Políticas Públicas, turma de 2024. O curso tem o objetivo de apresentar e discutir o uso de Inteligência Artificial (IA), em...',
      data_publicacao: '04/07/2024 10:08:26',
      produto_id: 0,
      produtos: '',
      editorias: 'ibge',
      imagens: '{"image_intro":"images\\/agenciadenoticias\\/ibge\\/2024_07\\/trilha-home.jpg","float_intro":"","image_intro_alt":"","image_intro_caption":"","image_fulltext":"images\\/agenciadenoticias\\/ibge\\/2024_07\\/trilha-home.jpg","float_fulltext":"","image_fulltext_alt":"","image_fulltext_caption":""}',
      produtos_relacionados: '',
      destaque: true,
      link: 'http://agenciadenoticias.ibge.gov.br/agencia-noticias/2012-agencia-de-noticias/noticias/40601-ence-abrira-pre-inscricoes-para-o-curso-inteligencia-artificial-em-politicas-publicas.html',
    },
    {
      id: 40549,
      tipo: 'Notícia',
      titulo: 'Produção industrial recua 0,9% em maio, segundo mês seguido de queda',
      introducao: 'O setor de veículos automotores, reboques e carrocerias recuou 11,7% em maio - Foto: Roberto Dziura Jr/AEN Na passagem de abril para maio, a produção industrial do país recuou 0,9%. Foi o segundo mês consecutivo de queda, período em que acumulou perda de...',
      data_publicacao: '03/07/2024 09:00:00',
      produto_id: 9294,
      produtos: '9294|PIM-PF Brasil#pimpf1|pesquisa-industrial-mensal-producao-fisica-brasil|2209',
      editorias: 'economicas',
      imagens: '{"image_intro":"images\\/agenciadenoticias\\/estatisticas_economicas\\/2024_07\\/PIM-Br_THUMBE-Roberto-DziuraJr-AEN.jpg","float_intro":"","image_intro_alt":"","image_intro_caption":"","image_fulltext":"images\\/agenciadenoticias\\/estatisticas_economicas\\/2024_07\\/PIM-Br_HOME-Roberto-DziuraJr-AEN.jpg","float_fulltext":"","image_fulltext_alt":"","image_fulltext_caption":""}',
      produtos_relacionados: '9294',
      destaque: true,
      link: 'http://agenciadenoticias.ibge.gov.br/agencia-noticias/2012-agencia-de-noticias/noticias/40549-producao-industrial-recua-0-9-em-maio-segundo-mes-seguido-de-queda.html',
    },
    {
      id: 40548,
      tipo: 'Release',
      titulo: 'Produção industrial recua 0,9% em maio',
      introducao: 'Em maio de 2024, a produção industrial nacional recuou 0,9% na comparação com abril, na série com ajuste sazonal, a segunda taxa negativa consecutiva, período em que acumulou perda de 1,7%. A média móvel trimestral teve variação negativa de 0,2% no...',
      data_publicacao: '03/07/2024 09:00:00',
      produto_id: 9294,
      produtos: '9294|PIM-PF Brasil#pimpf1|pesquisa-industrial-mensal-producao-fisica-brasil|2209',
      editorias: 'economicas',
      imagens: '{"image_intro":"images\\/agenciadenoticias\\/releases\\/PIM-PF-BR_Release1.png","float_intro":"","image_intro_alt":"","image_intro_caption":"","image_fulltext":"images\\/agenciadenoticias\\/releases\\/PIM-PF-BR_Release1.png","float_fulltext":"","image_fulltext_alt":"","image_fulltext_caption":""}',
      produtos_relacionados: '9294',
      destaque: true,
      link: 'http://agenciadenoticias.ibge.gov.br/agencia-sala-de-imprensa/2013-agencia-de-noticias/releases/40548-producao-industrial-recua-0-9-em-maio.html',
    },
    {
      id: 40569,
      tipo: 'Notícia',
      titulo: 'IBGE assina protocolo de intenções com Ministério da Previdência Social',
      introducao: 'O ministro da Previdência Social, Carlos Lupi, e o presidente do IBGE, Marcio Pochmann, firmaram o documento visando estabelecer Acordo de Cooperação Técnica - Foto: Marcio Costa/Agência IBGE Notícias O Instituto Brasileiro de Geografia e Estatística...',
      data_publicacao: '02/07/2024 05:06:08',
      produto_id: 0,
      produtos: '',
      editorias: 'ibge',
      imagens: '{"image_intro":"images\\/agenciadenoticias\\/ibge\\/2024_07\\/IBGE_CarlosLuoi_THUMB.jpg","float_intro":"","image_intro_alt":"","image_intro_caption":"","image_fulltext":"images\\/agenciadenoticias\\/ibge\\/2024_07\\/IBGE_CarlosLuoi_HOME.jpg","float_fulltext":"","image_fulltext_alt":"","image_fulltext_caption":""}',
      produtos_relacionados: '',
      destaque: true,
      link: 'http://agenciadenoticias.ibge.gov.br/agencia-noticias/2012-agencia-de-noticias/noticias/40569-ibge-assina-protocolo-de-intencoes-com-ministerio-da-previdencia-social.html',
    },
    {
      id: 40556,
      tipo: 'Notícia',
      titulo: 'Hub Regional para Big Data promove oficina sobre indicadores de mudanças climáticas',
      introducao: 'O V Workshop sobre o Uso de Big Data para Estatísticas Oficiais foi realizado entre os dias 24 e 28 de junho com o tema “ARIES (Artificial Intelligence for Environment and Sustainability) para Indicadores de Mitigação e Adaptação frente às Mudanças...',
      data_publicacao: '02/07/2024 01:49:05',
      produto_id: 0,
      produtos: '',
      editorias: 'ibge',
      imagens: '{"image_intro":"images\\/agenciadenoticias\\/ibge\\/2024_05\\/ENCE_HUB_Thumb.jpg","float_intro":"","image_intro_alt":"","image_intro_caption":"","image_fulltext":"images\\/agenciadenoticias\\/ibge\\/2024_05\\/ENCE_HUB_HOME.jpg","float_fulltext":"","image_fulltext_alt":"","image_fulltext_caption":""}',
      produtos_relacionados: '',
      destaque: true,
      link: 'http://agenciadenoticias.ibge.gov.br/agencia-noticias/2012-agencia-de-noticias/noticias/40556-hub-regional-para-big-data-promove-oficina-sobre-indicadores-de-mudancas-climaticas.html',
    },
    {
      id: 40547,
      tipo: 'Notícia',
      titulo: 'Em Nova Iorque, IBGE discute experiência brasileira em evento do UNFPA',
      introducao: 'A convite do UNFPA, Fundo de População da ONU, o presidente do Instituto Brasileiro de Geografia e Estatística (IBGE), Marcio Pochmann, participou nos dias 27 e 28 de junho, do Diálogo Global sobre Tecnologia: Moldando um futuro equitativo para todos. O...',
      data_publicacao: '01/07/2024 05:37:23',
      produto_id: 0,
      produtos: '',
      editorias: 'ibge',
      imagens: '{"image_intro":"images\\/agenciadenoticias\\/ibge\\/2024_07\\/unfpa-home.jpg","float_intro":"","image_intro_alt":"","image_intro_caption":"","image_fulltext":"images\\/agenciadenoticias\\/ibge\\/2024_07\\/unfpa-home.jpg","float_fulltext":"","image_fulltext_alt":"","image_fulltext_caption":""}',
      produtos_relacionados: '',
      destaque: true,
      link: 'http://agenciadenoticias.ibge.gov.br/agencia-noticias/2012-agencia-de-noticias/noticias/40547-em-nova-iorque-ibge-discute-experiencia-brasileira-em-evento-do-unfpa.html',
    },
    {
      id: 40526,
      tipo: 'Notícia',
      titulo: 'IBGE participa da Caravana Federativa Pará',
      introducao: 'O IBGE está pronto para participar da 11ª edição da Caravana Federativa, iniciativa do Governo Federal por meio das secretarias de Assuntos Federativos (Seaf) e de Relações Institucionais (SRI). No Pará, a Caravana Federativa será nos dias 4 e 5 de...',
      data_publicacao: '01/07/2024 10:00:00',
      produto_id: 0,
      produtos: '',
      editorias: 'ibge',
      imagens: '{"image_intro":"images\\/agenciadenoticias\\/ibge\\/2024_06\\/Caravana-Para-THUMB.jpg","float_intro":"","image_intro_alt":"","image_intro_caption":"","image_fulltext":"images\\/agenciadenoticias\\/ibge\\/2024_06\\/Caravana-Para-HOME.jpg","float_fulltext":"","image_fulltext_alt":"","image_fulltext_caption":""}',
      produtos_relacionados: '',
      destaque: true,
      link: 'http://agenciadenoticias.ibge.gov.br/agencia-noticias/2012-agencia-de-noticias/noticias/40526-ibge-participa-da-caravana-federativa-para.html',
    },
    {
      id: 40531,
      tipo: 'Notícia',
      titulo: 'IBGE disponibiliza Agenda de 1° a 7 de julho',
      introducao: 'Agenda IBGE traz a programação do instituto para a semana - Foto: Bel Corção/Brasil com S Divulgada hoje (1°), às 9h, a Agenda IBGE traz as programações do Instituto para a próxima semana. A Agenda traz as divulgações, as reuniões internas e externas e...',
      data_publicacao: '01/07/2024 09:00:00',
      produto_id: 0,
      produtos: '',
      editorias: 'ibge',
      imagens: '{"image_intro":"images\\/agenciadenoticias\\/ibge\\/2024_01\\/Agenda-IBGE_THUMB.jpg","float_intro":"","image_intro_alt":"","image_intro_caption":"","image_fulltext":"images\\/agenciadenoticias\\/ibge\\/2024_01\\/Agenda-IBGE_HOME.jpg","float_fulltext":"","image_fulltext_alt":"","image_fulltext_caption":""}',
      produtos_relacionados: '',
      destaque: true,
      link: 'http://agenciadenoticias.ibge.gov.br/agencia-noticias/2012-agencia-de-noticias/noticias/40531-ibge-disponibiliza-agenda-de-1-a-7-de-julho.html',
    },
    {
      id: 40527,
      tipo: 'Notícia',
      titulo: 'Inscrições para Conferência da Era Digital seguem abertas até o dia 20 de julho',
      introducao: 'As inscrições para a Conferência Nacional dos Agentes Produtores e Usuários de Dados sobre o tema da Soberania Nacional em Geociências, Estatísticas e Dados - os Riscos e Oportunidades da Era Digital seguem abertas até o dia 20 de julho. O evento...',
      data_publicacao: '28/06/2024 04:49:21',
      produto_id: 0,
      produtos: '',
      editorias: 'ibge',
      imagens: '{"image_intro":"images\\/agenciadenoticias\\/ibge\\/2024_06\\/Conferencia_Inscricao_THUMB.jpg","float_intro":"","image_intro_alt":"","image_intro_caption":"","image_fulltext":"images\\/agenciadenoticias\\/ibge\\/2024_06\\/Conferencia_Inscricao_HOME.jpg","float_fulltext":"","image_fulltext_alt":"","image_fulltext_caption":""}',
      produtos_relacionados: '',
      destaque: true,
      link: 'http://agenciadenoticias.ibge.gov.br/agencia-noticias/2012-agencia-de-noticias/noticias/40527-inscricoes-para-conferencia-da-era-digital-seguem-abertas-ate-o-dia-20-de-julho.html',
    },
    {
      id: 40525,
      tipo: 'Notícia',
      titulo: 'Presidente da SAP América Latina e Caribe é uma das palestrantes da Conferência da Era Digital',
      introducao: 'A presidente da SAP América Latina e Caribe, Cristina Palmaka, será uma das palestrantes da Conferência Nacional dos Agentes Produtores e Usuários de Dados sobre o tema da Soberania Nacional em Geociências, Estatísticas e Dados - os Riscos e...',
      data_publicacao: '28/06/2024 12:29:34',
      produto_id: 0,
      produtos: '',
      editorias: 'ibge',
      imagens: '{"image_intro":"images\\/agenciadenoticias\\/ibge\\/2024_06\\/Conferncia_Cristina_THUMB-2.jpg","float_intro":"","image_intro_alt":"","image_intro_caption":"","image_fulltext":"images\\/agenciadenoticias\\/ibge\\/2024_06\\/Conferncia_Cristina_HOME-2.jpg","float_fulltext":"","image_fulltext_alt":"","image_fulltext_caption":""}',
      produtos_relacionados: '',
      destaque: true,
      link: 'http://agenciadenoticias.ibge.gov.br/agencia-noticias/2012-agencia-de-noticias/noticias/40525-presidente-da-sap-america-latina-e-caribe-e-uma-das-palestrantes-da-conferencia-da-era-digital.html',
    },
    {
      id: 40507,
      tipo: 'Notícia',
      titulo: 'IBGE lança Mapa Político do Brasil com atualizações do Censo 2022',
      introducao: 'Por ter dimensões menores, o Mapa Político do Brasil na escala 1:5.000.000 representa as sedes dos municípios selecionados para a escala - Foto: Arte sobre mockup O IBGE disponibiliza a partir de hoje, 28, a versão 2023 dos Mapas Políticos do Brasil nas...',
      data_publicacao: '28/06/2024 10:00:00',
      produto_id: 0,
      produtos: '',
      editorias: 'geociencias',
      imagens: '{"image_intro":"images\\/agenciadenoticias\\/geociencias\\/2024_06\\/mapa-poltico_THUMB.jpg","float_intro":"","image_intro_alt":"","image_intro_caption":"","image_fulltext":"images\\/agenciadenoticias\\/geociencias\\/2024_06\\/mapa-poltico_HOME.jpg","float_fulltext":"","image_fulltext_alt":"","image_fulltext_caption":""}',
      produtos_relacionados: '',
      destaque: true,
      link: 'http://agenciadenoticias.ibge.gov.br/agencia-noticias/2012-agencia-de-noticias/noticias/40507-ibge-lanca-mapa-politico-do-brasil-com-atualizacoes-do-censo-2022.html',
    },
    {
      id: 40519,
      tipo: 'Notícia',
      titulo: 'IBGE define bioma predominante em cada município brasileiro para fins estatísticos',
      introducao: 'A Mata Atlântica é o bioma predominante em quase metade (49,2%) dos municípios brasileiros - Foto: Tomaz Silva/Agência Brasil Embora a Amazônia seja o bioma com maior área no território nacional, a Mata Atlântica é predominante no maior número de...',
      data_publicacao: '28/06/2024 10:00:00',
      produto_id: 0,
      produtos: '',
      editorias: 'geociencias',
      imagens: '{"image_intro":"images\\/agenciadenoticias\\/geociencias\\/2024_06\\/Bioma_THUMB_Tomaz-Silva-Agncia-Brasil.jpg","float_intro":"","image_intro_alt":"","image_intro_caption":"","image_fulltext":"images\\/agenciadenoticias\\/geociencias\\/2024_06\\/Bioma_HOME_Tomaz-Silva-Agncia-Brasil.jpg","float_fulltext":"","image_fulltext_alt":"","image_fulltext_caption":""}',
      produtos_relacionados: '',
      destaque: true,
      link: 'http://agenciadenoticias.ibge.gov.br/agencia-noticias/2012-agencia-de-noticias/noticias/40519-ibge-define-bioma-predominante-em-cada-municipio-brasileiro-para-fins-estatisticos.html',
    },
    {
      id: 40520,
      tipo: 'Notícia',
      titulo: 'Desemprego recua para 7,1%, menor taxa para um trimestre encerrado em maio desde 2014 ',
      introducao: 'População ocupada no setor privado chega a 52,0 milhões, novo recorde da série histórica da PNAD Contínua - Foto: Rodrigo Félix Leal/AEN-PR No trimestre móvel encerrado em maio de 2024, a taxa de desocupação recuou 0,7 ponto percentual (p.p.) frente ao...',
      data_publicacao: '28/06/2024 09:00:00',
      produto_id: 9171,
      produtos: '9171|Divulgação mensal#pnadc1|pesquisa-nacional-por-amostra-de-domicilios-continua-mensal|2511',
      editorias: 'sociais',
      imagens: '{"image_intro":"images\\/agenciadenoticias\\/estatisticas_sociais\\/2024_06\\/PNADC-THUMB-RodrigoFelixLeal-AEN.jpg","float_intro":"","image_intro_alt":"","image_intro_caption":"","image_fulltext":"images\\/agenciadenoticias\\/estatisticas_sociais\\/2024_06\\/PNADC-HOME-RodrigoFelixLeal-AEN.jpg","float_fulltext":"","image_fulltext_alt":"","image_fulltext_caption":""}',
      produtos_relacionados: '9171',
      destaque: true,
      link: 'http://agenciadenoticias.ibge.gov.br/agencia-noticias/2012-agencia-de-noticias/noticias/40520-desemprego-recua-para-7-1-menor-taxa-para-um-trimestre-encerrado-em-maio-desde-2014.html',
    },
    {
      id: 40518,
      tipo: 'Release',
      titulo: 'PNAD Contínua: taxa de desocupação é de 7,1% e taxa de subutilização é de 16,8% no trimestre encerrado em maio',
      introducao: 'A taxa de desocupação (7,1%) no trimestre encerrado em maio de 2024 recuou 0,7 ponto percentual (p.p.) frente ao trimestre de dezembro a fevereiro de 2024 (7,8%) e caiu 1,2 p.p. ante o mesmo trimestre móvel de 2023 (8,3%). Essa foi a menor taxa de...',
      data_publicacao: '28/06/2024 09:00:00',
      produto_id: 9171,
      produtos: '9171|Divulgação mensal#pnadc1|pesquisa-nacional-por-amostra-de-domicilios-continua-mensal|2511',
      editorias: 'sociais',
      imagens: '{"image_intro":"images\\/agenciadenoticias\\/releases\\/PNAD_C_Mensal_Release.png","float_intro":"","image_intro_alt":"","image_intro_caption":"","image_fulltext":"images\\/agenciadenoticias\\/releases\\/PNAD_C_Mensal_Release.png","float_fulltext":"","image_fulltext_alt":"","image_fulltext_caption":""}',
      produtos_relacionados: '9171',
      destaque: true,
      link: 'http://agenciadenoticias.ibge.gov.br/agencia-sala-de-imprensa/2013-agencia-de-noticias/releases/40518-pnad-continua-taxa-de-desocupacao-e-de-7-1-e-taxa-de-subutilizacao-e-de-16-8-no-trimestre-encerrado-em-maio.html',
    },
    {
      id: 40487,
      tipo: 'Notícia',
      titulo: 'Fabricação de produtos alimentícios foi a principal atividade industrial do país em 2022',
      introducao: 'Fabricação de produtos alimentícios foi a principal atividade industrial em 13 das 27 unidades da federação - Foto: Gilson Abreu/AEN Em 2022, a Fabricação de produtos alimentícios se manteve como o segmento industrial de maior importância para a...',
      data_publicacao: '27/06/2024 10:00:00',
      produto_id: 9042,
      produtos: '9042|PIA-Empresa#pia1|pesquisa-industrial-anual|2016',
      editorias: 'economicas',
      imagens: '{"image_intro":"images\\/agenciadenoticias\\/estatisticas_economicas\\/2024_06\\/PIA_empresa_THUMB_Gilson-Abreu-AEN.jpg","float_intro":"","image_intro_alt":"","image_intro_caption":"","image_fulltext":"images\\/agenciadenoticias\\/estatisticas_economicas\\/2024_06\\/PIA_Empresa_HOME_Gilson-Abreu-AEN.jpg","float_fulltext":"","image_fulltext_alt":"","image_fulltext_caption":""}',
      produtos_relacionados: '9042',
      destaque: true,
      link: 'http://agenciadenoticias.ibge.gov.br/agencia-noticias/2012-agencia-de-noticias/noticias/40487-fabricacao-de-produtos-alimenticios-foi-a-principal-atividade-industrial-do-pais-em-2022.html',
    },
    {
      id: 40486,
      tipo: 'Notícia',
      titulo: 'Em 2022, minério de ferro perde posição e petróleo bruto se torna o principal produto industrial do país',
      introducao: 'Petróleo bruto se tornou o principal produto da indústria nacional em 2022 - Foto: Agência Petrobras O IBGE divulgou, nesta quinta-feira (27), a Pesquisa Industrial Anual-Produto (PIA-Produto) 2022, que investigou cerca de 3.400 produtos fabricados pelas...',
      data_publicacao: '27/06/2024 10:00:00',
      produto_id: 9044,
      produtos: '9044|PIA-Produto#pia2|pesquisa-industrial-anual-produto|2896',
      editorias: 'economicas',
      imagens: '{"image_intro":"images\\/agenciadenoticias\\/estatisticas_economicas\\/2024_06\\/PIA-Produt_THUMB_Agncia-Petrobras.jpg","float_intro":"","image_intro_alt":"","image_intro_caption":"","image_fulltext":"images\\/agenciadenoticias\\/estatisticas_economicas\\/2024_06\\/PIA-Produt_HOME_Agncia-Petrobras.jpg","float_fulltext":"","image_fulltext_alt":"","image_fulltext_caption":""}',
      produtos_relacionados: '9044',
      destaque: true,
      link: 'http://agenciadenoticias.ibge.gov.br/agencia-noticias/2012-agencia-de-noticias/noticias/40486-em-2022-minerio-de-ferro-perde-posicao-e-petroleo-bruto-se-torna-o-principal-produto-industrial-do-pais.html',
    },
    {
      id: 40488,
      tipo: 'Release',
      titulo: 'Índice de Preços ao Produtor (IPP) é de 0,45% em maio ',
      introducao: 'Em maio de 2024, os preços da indústria variaram 0,45% frente a abril, quarto resultado positivo seguido nesse indicador. Nessa comparação, 15 das 24 atividades industriais tiveram variações positivas de preços. O acumulado no ano foi de 1,37%, enquanto...',
      data_publicacao: '27/06/2024 09:00:00',
      produto_id: 9282,
      produtos: '9282|Índice de Preços ao Produtor - Indústrias Extrativas e de Transformação|indice-de-precos-ao-produtor-industrias-extrativas-e-de-transformacao|2081',
      editorias: 'economicas',
      imagens: '{"image_intro":"images\\/agenciadenoticias\\/releases\\/IPP_Release.png","float_intro":"","image_intro_alt":"","image_intro_caption":"","image_fulltext":"images\\/agenciadenoticias\\/releases\\/IPP_Release.png","float_fulltext":"","image_fulltext_alt":"","image_fulltext_caption":""}',
      produtos_relacionados: '9282',
      destaque: true,
      link: 'http://agenciadenoticias.ibge.gov.br/agencia-sala-de-imprensa/2013-agencia-de-noticias/releases/40488-indice-de-precos-ao-produtor-ipp-e-de-0-45-em-maio.html',
    },
    {
      id: 40489,
      tipo: 'Notícia',
      titulo: 'Preços da indústria crescem 0,45% em maio, quarto resultado positivo seguido',
      introducao: 'Setor de alimentos foi o de maior destaque no índice geral, com influência de 0,45 ponto percentual - Foto: José Fernando Ogura/AEN Os preços da indústria nacional cresceram 0,45% em maio na comparação com o resultado de abril, que havia sido de 0,67%....',
      data_publicacao: '27/06/2024 09:00:00',
      produto_id: 9282,
      produtos: '9282|Índice de Preços ao Produtor - Indústrias Extrativas e de Transformação|indice-de-precos-ao-produtor-industrias-extrativas-e-de-transformacao|2081',
      editorias: 'economicas',
      imagens: '{"image_intro":"images\\/agenciadenoticias\\/estatisticas_economicas\\/2024_06\\/IPP_THUMB_Jose-Fernando-Ogura-AEN.jpg","float_intro":"","image_intro_alt":"","image_intro_caption":"","image_fulltext":"images\\/agenciadenoticias\\/estatisticas_economicas\\/2024_06\\/IPP_HOME_Jose-Fernando-Ogura-AEN.jpg","float_fulltext":"","image_fulltext_alt":"","image_fulltext_caption":""}',
      produtos_relacionados: '9282',
      destaque: true,
      link: 'http://agenciadenoticias.ibge.gov.br/agencia-noticias/2012-agencia-de-noticias/noticias/40489-precos-da-industria-crescem-0-45-em-maio-quarto-resultado-positivo-seguido.html',
    },
    {
      id: 40490,
      tipo: 'Notícia',
      titulo: 'IBGE lança versão digital do Anuário Estatístico do Brasil em evento na Casa Brasil IBGE ',
      introducao: 'Autoridades e convidados prestigiaram o lançamento do AEB na Casa Brasil IBGE - Foto: Marcio Costa/Agência IBGE Notícias O Instituto Brasileiro de Geografia e Estatística (IBGE) lançou Brasil nesta quarta-feira, 26, em evento na Casa Brasil IBGE,...',
      data_publicacao: '26/06/2024 05:13:18',
      produto_id: 0,
      produtos: '',
      editorias: 'ibge',
      imagens: '{"image_intro":"images\\/agenciadenoticias\\/ibge\\/2024_06\\/anuario-estatistico-home.jpg","float_intro":"","image_intro_alt":"","image_intro_caption":"","image_fulltext":"images\\/agenciadenoticias\\/ibge\\/2024_06\\/anuario-estatistico-home.jpg","float_fulltext":"","image_fulltext_alt":"","image_fulltext_caption":""}',
      produtos_relacionados: '',
      destaque: true,
      link: 'http://agenciadenoticias.ibge.gov.br/agencia-noticias/2012-agencia-de-noticias/noticias/40490-ibge-lanca-versao-digital-do-anuario-estatistico-do-brasil-em-evento-na-casa-brasil-ibge.html',
    },
    {
      id: 40483,
      tipo: 'Notícia',
      titulo: 'Casa Brasil IBGE  oferece cursos de férias ',
      introducao: 'Como parte das ações promovidas pelo IBGE para disseminar o aprendizado do acesso aos seus dados e informações, serão oferecidas oficinas presenciais no período de férias escolares de forma gratuita, em conformidade com as diretrizes temáticas do...',
      data_publicacao: '26/06/2024 11:15:51',
      produto_id: 0,
      produtos: '',
      editorias: 'ibge',
      imagens: '{"image_intro":"images\\/agenciadenoticias\\/ibge\\/2024_06\\/Curso-Ferias_THUMB.jpg","float_intro":"","image_intro_alt":"","image_intro_caption":"","image_fulltext":"images\\/agenciadenoticias\\/ibge\\/2024_06\\/Curso-Ferias_HOME.jpg","float_fulltext":"","image_fulltext_alt":"","image_fulltext_caption":""}',
      produtos_relacionados: '',
      destaque: true,
      link: 'http://agenciadenoticias.ibge.gov.br/agencia-noticias/2012-agencia-de-noticias/noticias/40483-casa-brasil-ibge-oferece-cursos-de-ferias.html',
    },
    {
      id: 40482,
      tipo: 'Notícia',
      titulo: 'IBGE lança a etapa Brasil do Concurso de Pôsteres na Casa Brasil IBGE',
      introducao: 'O IBGE lança hoje, 26 de junho, a etapa Brasil do Concurso Internacional de Pôsteres Estatísticos 2024-2025 por ocasião da divulgação do Anuário Estatístico do Brasil, na Casa Brasil IBGE. A iniciativa é do instituto, por meio de sua escola de...',
      data_publicacao: '26/06/2024 10:49:55',
      produto_id: 0,
      produtos: '',
      editorias: 'ibge',
      imagens: '{"image_intro":"images\\/agenciadenoticias\\/ibge\\/2024_06\\/Concuso-ISLP_THUMB2.jpg","float_intro":"","image_intro_alt":"","image_intro_caption":"","image_fulltext":"images\\/agenciadenoticias\\/ibge\\/2024_06\\/Concuso-ISLP_HOME2.jpg","float_fulltext":"","image_fulltext_alt":"","image_fulltext_caption":""}',
      produtos_relacionados: '',
      destaque: true,
      link: 'http://agenciadenoticias.ibge.gov.br/agencia-noticias/2012-agencia-de-noticias/noticias/40482-ibge-lanca-a-etapa-brasil-do-concurso-de-posteres-na-casa-brasil-ibge.html',
    },
    {
      id: 40475,
      tipo: 'Notícia',
      titulo: 'Prévia da inflação de junho fica em 0,39%',
      introducao: 'Aumentos da batata inglesa, do leite longa vida, do arroz e do tomate puxaram alta do grupo Alimentação e Bebidas - Foto: Helena Pontes/Agência IBGE Notícias A prévia da inflação de junho ficou em 0,39%, após taxa de 0,44% registrada em maio. O Índice...',
      data_publicacao: '26/06/2024 09:00:00',
      produto_id: 9260,
      produtos: '9260|Índice Nacional de Preços ao Consumidor Amplo 15|indice-nacional-de-precos-ao-consumidor-amplo-15|2213',
      editorias: 'economicas',
      imagens: '{"image_intro":"images\\/agenciadenoticias\\/estatisticas_economicas\\/2024_06\\/IPCA15_THUMB_HelenaPontes.jpg","float_intro":"","image_intro_alt":"","image_intro_caption":"","image_fulltext":"images\\/agenciadenoticias\\/estatisticas_economicas\\/2024_06\\/IPCA15_HOME_HelenaPontes.jpg","float_fulltext":"","image_fulltext_alt":"","image_fulltext_caption":""}',
      produtos_relacionados: '9260',
      destaque: true,
      link: 'http://agenciadenoticias.ibge.gov.br/agencia-noticias/2012-agencia-de-noticias/noticias/40475-previa-da-inflacao-de-junho-fica-em-0-39.html',
    },
    {
      id: 40474,
      tipo: 'Release',
      titulo: 'IPCA-15 foi de 0,39% em junho',
      introducao: 'O Índice Nacional de Preços ao Consumidor Amplo 15 (IPCA-15) foi de 0,39% em junho, 0,05 ponto percentual abaixo da taxa de maio (0,44%). O IPCA-E, acumulado trimestral do IPCA-15, ficou em 1,04%, abaixo dos 1,12% registrados no mesmo período de 2023....',
      data_publicacao: '26/06/2024 09:00:00',
      produto_id: 9260,
      produtos: '9260|Índice Nacional de Preços ao Consumidor Amplo 15|indice-nacional-de-precos-ao-consumidor-amplo-15|2213',
      editorias: 'economicas',
      imagens: '{"image_intro":"images\\/agenciadenoticias\\/releases\\/IPCA15_Release.png","float_intro":"","image_intro_alt":"","image_intro_caption":"","image_fulltext":"images\\/agenciadenoticias\\/releases\\/IPCA15_Release.png","float_fulltext":"","image_fulltext_alt":"","image_fulltext_caption":""}',
      produtos_relacionados: '9260',
      destaque: true,
      link: 'http://agenciadenoticias.ibge.gov.br/agencia-sala-de-imprensa/2013-agencia-de-noticias/releases/40474-ipca-15-foi-de-0-39-em-junho.html',
    },
    {
      id: 40477,
      tipo: 'Notícia',
      titulo: 'Com inauguração de totem interativo na UERJ, IBGE abre as inscrições para Conferência da Era Digital',
      introducao: 'O Instituto Brasileiro de Geografia e Estatística (IBGE) abriu nesta terça-feira (25), com a inauguração de um totem interativo do Instituto na Universidade Estadual do Rio de Janeiro (UERJ), as inscrições para a Conferência Nacional dos Agentes...',
      data_publicacao: '25/06/2024 04:59:39',
      produto_id: 0,
      produtos: '',
      editorias: 'ibge',
      imagens: '{"image_intro":"images\\/agenciadenoticias\\/ibge\\/2024_06\\/Banner_Conferncia.jpg","float_intro":"","image_intro_alt":"","image_intro_caption":"","image_fulltext":"images\\/agenciadenoticias\\/ibge\\/2024_06\\/Banner_Conferncia.jpg","float_fulltext":"","image_fulltext_alt":"","image_fulltext_caption":""}',
      produtos_relacionados: '',
      destaque: true,
      link: 'http://agenciadenoticias.ibge.gov.br/agencia-noticias/2012-agencia-de-noticias/noticias/40477-com-inauguracao-de-totem-interativo-na-uerj-ibge-abre-as-inscricoes-para-conferencia-da-era-digital.html',
    },
    {
      id: 40476,
      tipo: 'Notícia',
      titulo: 'IBGE promove evento em Alagoas para fortalecer relação com empresas e analisar impacto econômico das pesquisas',
      introducao: 'A Superintendência do IBGE em Alagoas promove, na próxima quarta-feira (3), o evento "Diálogos Externos IBGE: A importância das pesquisas em empresas para a economia de Alagoas". O encontro é uma oportunidade para empresários, contadores e a sociedade em...',
      data_publicacao: '25/06/2024 04:43:02',
      produto_id: 0,
      produtos: '',
      editorias: 'ibge',
      imagens: '{"image_intro":"images\\/agenciadenoticias\\/ibge\\/2024_06\\/IBGE_DialogosExternos_HOME.jpg","float_intro":"","image_intro_alt":"","image_intro_caption":"","image_fulltext":"images\\/agenciadenoticias\\/ibge\\/2024_06\\/IBGE_DialogosExternos_HOME.jpg","float_fulltext":"","image_fulltext_alt":"","image_fulltext_caption":""}',
      produtos_relacionados: '',
      destaque: true,
      link: 'http://agenciadenoticias.ibge.gov.br/agencia-noticias/2012-agencia-de-noticias/noticias/40476-ibge-promove-evento-em-alagoas-para-fortalecer-relacao-com-empresas-e-analisar-impacto-economico-das-pesquisas.html',
    },
    {
      id: 40459,
      tipo: 'Notícia',
      titulo: 'Já está disponível a Agenda IBGE para a semana dos dias 24 a 30 de junho',
      introducao: 'Agenda IBGE traz a programação do instituto para a semana - Foto: Bel Corção/Brasil com S Divulgada hoje (24), a Agenda IBGE traz as programações do Instituto, as reuniões internas e externas, os eventos e os compromissos de diversas áreas, desde a...',
      data_publicacao: '24/06/2024 09:00:00',
      produto_id: 0,
      produtos: '',
      editorias: 'ibge',
      imagens: '{"image_intro":"images\\/agenciadenoticias\\/ibge\\/2024_01\\/Agenda-IBGE_THUMB.jpg","float_intro":"","image_intro_alt":"","image_intro_caption":"","image_fulltext":"images\\/agenciadenoticias\\/ibge\\/2024_01\\/Agenda-IBGE_HOME.jpg","float_fulltext":"","image_fulltext_alt":"","image_fulltext_caption":""}',
      produtos_relacionados: '',
      destaque: true,
      link: 'http://agenciadenoticias.ibge.gov.br/agencia-noticias/2012-agencia-de-noticias/noticias/40459-ja-esta-disponivel-a-agenda-ibge-para-a-semana-dos-dias-24-a-30-de-junho.html',
    },
    {
      id: 40451,
      tipo: 'Notícia',
      titulo: 'Casa Brasil IBGE abre as portas para estudantes do ensino fundamental e médio ',
      introducao: 'Para conhecimento e compreensão do mapa-mundi, estudantes puderam caminhar e interagir sobre ele, com a dimensão de 10 x 6 metros - Foto: Marcio Costa/Agência IBGE Notícias O Instituto Brasileiro de Geografia e Estatística (IBGE) abriu as portas nessa...',
      data_publicacao: '21/06/2024 10:30:00',
      produto_id: 0,
      produtos: '',
      editorias: 'ibge',
      imagens: '{"image_intro":"images\\/agenciadenoticias\\/ibge\\/2024_06\\/CasaIBGE_THUMB_MarcioCosta.jpg","float_intro":"","image_intro_alt":"","image_intro_caption":"","image_fulltext":"images\\/agenciadenoticias\\/ibge\\/2024_06\\/CasaIBGE_HOME_MarcioCosta.jpg","float_fulltext":"","image_fulltext_alt":"","image_fulltext_caption":""}',
      produtos_relacionados: '',
      destaque: true,
      link: 'http://agenciadenoticias.ibge.gov.br/agencia-noticias/2012-agencia-de-noticias/noticias/40451-casa-brasil-ibge-abre-as-portas-para-estudantes-do-ensino-fundamental-e-medio.html',
    },
    {
      id: 40445,
      tipo: 'Notícia',
      titulo: 'Em 2023, número de sindicalizados cai para 8,4 milhões, o menor desde 2012',
      introducao: 'Em 2023, o número de sindicalizados caiu 7,8%, o equivalente a 713 mil pessoas - Foto: Paulo Pinto/Agência Brasil A sindicalização segue perdendo força entre os trabalhadores do país. Em 2023, apenas 8,4% dos 100,7 milhões de ocupados eram associados a...',
      data_publicacao: '21/06/2024 10:00:00',
      produto_id: 17270,
      produtos: '17270|Divulgação anual#pnadc3|pnad-continua|2511',
      editorias: 'sociais',
      imagens: '{"image_intro":"images\\/agenciadenoticias\\/estatisticas_sociais\\/2024_06\\/PNAD-Trab_THUMB_Paulo-Pinto-Agncia-Brasil.jpg","float_intro":"","image_intro_alt":"","image_intro_caption":"","image_fulltext":"images\\/agenciadenoticias\\/estatisticas_sociais\\/2024_06\\/PNAD-Trab_HOME_Paulo-Pinto-Agncia-Brasil.jpg","float_fulltext":"","image_fulltext_alt":"","image_fulltext_caption":""}',
      produtos_relacionados: '17270',
      destaque: true,
      link: 'http://agenciadenoticias.ibge.gov.br/agencia-noticias/2012-agencia-de-noticias/noticias/40445-em-2023-numero-de-sindicalizados-cai-para-8-4-milhoes-o-menor-desde-2012.html',
    },
    {
      id: 40448,
      tipo: 'Notícia',
      titulo: 'IBGE realiza mais de 180 atendimentos em Caravana Federativa no Piauí',
      introducao: 'Décima edição da Caravana Federativa conta com presença do governador do Piauí, Rafael Fonteles, do ministro Wellington Dias e demais autoridades federais, estaduais e municipais - Foto: Juliana Macedo/IBGE O IBGE realizou nesta quinta-feira, 20, os...',
      data_publicacao: '20/06/2024 05:10:05',
      produto_id: 0,
      produtos: '',
      editorias: 'ibge',
      imagens: '{"image_intro":"images\\/agenciadenoticias\\/ibge\\/2024_06\\/carav-pi-01.jpg","float_intro":"","image_intro_alt":"","image_intro_caption":"","image_fulltext":"images\\/agenciadenoticias\\/ibge\\/2024_06\\/carav-pi-01.jpg","float_fulltext":"","image_fulltext_alt":"","image_fulltext_caption":""}',
      produtos_relacionados: '',
      destaque: true,
      link: 'http://agenciadenoticias.ibge.gov.br/agencia-noticias/2012-agencia-de-noticias/noticias/40448-ibge-realiza-mais-de-150-atendimentos-em-caravana-federativa-no-piaui.html',
    },
    {
      id: 40449,
      tipo: 'Notícia',
      titulo: 'IBGE lança oficina para gestores públicos na Caravana Federativa do Piauí',
      introducao: 'Como parte das ações do IBGE na Caranava Federativa do Piauí, os gestores do estado poderão participar de forma gratuita da oficina "Políticas públicas na era digital: Dominando os dados do IBGE". A Caravana Federativa do Piauí ocorre nos dias 20 e 21 de...',
      data_publicacao: '20/06/2024 05:00:59',
      produto_id: 0,
      produtos: '',
      editorias: 'ibge',
      imagens: '{"image_intro":"images\\/agenciadenoticias\\/ibge\\/2024_06\\/oficina-piaui-THUMBS-caravana.jpg","float_intro":"","image_intro_alt":"","image_intro_caption":"","image_fulltext":"images\\/agenciadenoticias\\/ibge\\/2024_06\\/oficina-piaui-HOME-caravana.jpg","float_fulltext":"","image_fulltext_alt":"","image_fulltext_caption":""}',
      produtos_relacionados: '',
      destaque: true,
      link: 'http://agenciadenoticias.ibge.gov.br/agencia-noticias/2012-agencia-de-noticias/noticias/40449-ibge-lanca-oficina-para-gestores-publicos-na-caravana-federativa-do-piaui.html',
    },
  ],
};

export const additionalNews = {
  items: [
    {
      id: 123123,
      tipo: 'Notícia',
      titulo: 'ENCE abrirá pré-inscrições para o curso Inteligência Artificial em Políticas Públicas',
      introducao: 'A Escola Nacional de Ciências Estatísticas (ENCE) abrirá pré-inscrições em 5 de julho para o curso Inteligência Artificial em Políticas Públicas, turma de 2024. O curso tem o objetivo de apresentar e discutir o uso de Inteligência Artificial (IA), em...',
      data_publicacao: '04/07/2024 10:08:26',
      produto_id: 0,
      produtos: '',
      editorias: 'ibge',
      imagens: '{"image_intro":"images\\/agenciadenoticias\\/ibge\\/2024_07\\/trilha-home.jpg","float_intro":"","image_intro_alt":"","image_intro_caption":"","image_fulltext":"images\\/agenciadenoticias\\/ibge\\/2024_07\\/trilha-home.jpg","float_fulltext":"","image_fulltext_alt":"","image_fulltext_caption":""}',
      produtos_relacionados: '',
      destaque: true,
      link: 'http://agenciadenoticias.ibge.gov.br/agencia-noticias/2012-agencia-de-noticias/noticias/40601-ence-abrira-pre-inscricoes-para-o-curso-inteligencia-artificial-em-politicas-publicas.html',
    },
    {
      id: 3123123,
      tipo: 'Notícia',
      titulo: 'Produção industrial recua 0,9% em maio, segundo mês seguido de queda',
      introducao: 'O setor de veículos automotores, reboques e carrocerias recuou 11,7% em maio - Foto: Roberto Dziura Jr/AEN Na passagem de abril para maio, a produção industrial do país recuou 0,9%. Foi o segundo mês consecutivo de queda, período em que acumulou perda de...',
      data_publicacao: '03/07/2024 09:00:00',
      produto_id: 9294,
      produtos: '9294|PIM-PF Brasil#pimpf1|pesquisa-industrial-mensal-producao-fisica-brasil|2209',
      editorias: 'economicas',
      imagens: '{"image_intro":"images\\/agenciadenoticias\\/estatisticas_economicas\\/2024_07\\/PIM-Br_THUMBE-Roberto-DziuraJr-AEN.jpg","float_intro":"","image_intro_alt":"","image_intro_caption":"","image_fulltext":"images\\/agenciadenoticias\\/estatisticas_economicas\\/2024_07\\/PIM-Br_HOME-Roberto-DziuraJr-AEN.jpg","float_fulltext":"","image_fulltext_alt":"","image_fulltext_caption":""}',
      produtos_relacionados: '9294',
      destaque: true,
      link: 'http://agenciadenoticias.ibge.gov.br/agencia-noticias/2012-agencia-de-noticias/noticias/40549-producao-industrial-recua-0-9-em-maio-segundo-mes-seguido-de-queda.html',
    },
  ]
}

export const searchNews = {
  "items": [
    {
      "id": 38398,
      "tipo": "Notícia",
      "titulo": "Encontro do IBGE termina com entrega de 12 diretrizes para o 90º aniversário do Instituto",
      "introducao": "No Encontro Diálogos IBGE 90 anos, realizado nos dias 16 e 17 de novembro na Unidade de Parada Lucas (RJ), foram escolhidas 12 diretrizes que vão nortear os próximos 3 anos do IBGE - Foto: Licia Rubinstein\\Agência IBGE Notícias O IBGE encerrou, no fim da...",
      "data_publicacao": "17/11/2023 08:44:00",
      "produto_id": 0,
      "produtos": "",
      "editorias": "ibge",
      "imagens": "{\"image_intro\":\"images\\/agenciadenoticias\\/ibge\\/2023_11\\/Encerramento_THUMB.jpg\",\"float_intro\":\"\",\"image_intro_alt\":\"\",\"image_intro_caption\":\"\",\"image_fulltext\":\"images\\/agenciadenoticias\\/ibge\\/2023_11\\/Encerramento_HOME.jpg\",\"float_fulltext\":\"\",\"image_fulltext_alt\":\"\",\"image_fulltext_caption\":\"\"}",
      "produtos_relacionados": "",
      "destaque": true,
      "link": "http://agenciadenoticias.ibge.gov.br/agencia-noticias/2012-agencia-de-noticias/noticias/38398-encontro-de-servidores-do-ibge-termina-com-entrega-de-12-diretrizes-para-o-90-aniversario-do-instituto.html"
    },
    {
      "id": 38378,
      "tipo": "Notícia",
      "titulo": "6ª edição do Seminário IBGE de Portas Abertas para a Escola propõe levar resultados do Censo ao público infantojuvenil ",
      "introducao": "Citando a missão do IBGE, a gerente de assuntos educacionais Renata Corrêa ressaltou os desafios para disseminar as informações estatísticas - Foto: Licia Rubinstein/Agência IBGE Notícias A ENCE – Escola Nacional de Ciências Estatísticas – sediou, nesta...",
      "data_publicacao": "14/11/2023 05:52:41",
      "produto_id": 0,
      "produtos": "",
      "editorias": "ibge",
      "imagens": "{\"image_intro\":\"images\\/agenciadenoticias\\/ibge\\/2023_11\\/Educa_thumb.jpg\",\"float_intro\":\"\",\"image_intro_alt\":\"\",\"image_intro_caption\":\"\",\"image_fulltext\":\"images\\/agenciadenoticias\\/ibge\\/2023_11\\/Educa_home.jpg\",\"float_fulltext\":\"\",\"image_fulltext_alt\":\"\",\"image_fulltext_caption\":\"\"}",
      "produtos_relacionados": "",
      "destaque": true,
      "link": "http://agenciadenoticias.ibge.gov.br/agencia-noticias/2012-agencia-de-noticias/noticias/38378-6-edicao-do-seminario-ibge-de-portas-abertas-para-a-escola-propoe-levar-resultados-do-censo-ao-publico-infantojuvenil.html"
    },
    {
      "id": 38145,
      "tipo": "Notícia",
      "titulo": "IBGE realiza cerimônia de entrega do 1º Prêmio Fotográfico do Censo Demográfico 2022",
      "introducao": "Ganhadores do Prêmio Fotográfico se reúnem no palco do auditório ao final do evento - Foto: Victor Otsuka/IBGE A cerimônia de entrega do 1º Prêmio Fotográfico do Censo Demográfico 2022 foi realizada, no dia 16 de outubro, na Assembleia Legislativa do...",
      "data_publicacao": "19/10/2023 11:18:07",
      "produto_id": 0,
      "produtos": "",
      "editorias": "ibge;censo2020",
      "imagens": "{\"image_intro\":\"images\\/agenciadenoticias\\/ibge\\/2023_10\\/PremioFotografico-THUMB-VictorOtsuka-IBGE.jpg\",\"float_intro\":\"\",\"image_intro_alt\":\"\",\"image_intro_caption\":\"\",\"image_fulltext\":\"images\\/agenciadenoticias\\/ibge\\/2023_10\\/PremioFotografico-HOME-VictorOtsuka-IBGE.jpg\",\"float_fulltext\":\"\",\"image_fulltext_alt\":\"\",\"image_fulltext_caption\":\"\"}",
      "produtos_relacionados": "",
      "destaque": true,
      "link": "http://agenciadenoticias.ibge.gov.br/agencia-noticias/2012-agencia-de-noticias/noticias/38145-ibge-realiza-cerimonia-de-entrega-do-1-premio-fotografico-do-censo-demografico-2022.html"
    },
    {
      "id": 26712,
      "tipo": "Notícia",
      "titulo": "Conheça histórias e motivações por trás do trabalho de floricultores",
      "introducao": "Laerte Correia em sua produção de flores em Ivoti, no Rio Grande do Sul - Foto: Satoshi Suzuki O engenheiro agrônomo Laerte Correia começou a produzir flores em 2007, aos 56, após anos prestando assistência técnica a produtores do município de Ivoti, no...",
      "data_publicacao": "24/01/2020 02:00:00",
      "produto_id": 21814,
      "produtos": "21814|2017#2017 censo agropecuário|2017-censo-agropecuario|2017",
      "editorias": "seriesespeciais",
      "imagens": "{\"image_intro\":\"images\\/agenciadenoticias\\/ibge\\/2020_01\\/flores_thumb.jpg\",\"float_intro\":\"\",\"image_intro_alt\":\"\",\"image_intro_caption\":\"\",\"image_fulltext\":\"images\\/agenciadenoticias\\/ibge\\/2020_01\\/flores_home.jpg\",\"float_fulltext\":\"\",\"image_fulltext_alt\":\"\",\"image_fulltext_caption\":\"\"}",
      "produtos_relacionados": "21814",
      "destaque": true,
      "link": "http://agenciadenoticias.ibge.gov.br/agencia-noticias/2012-agencia-de-noticias/noticias/26712-conheca-historias-e-motivacoes-por-tras-do-trabalho-de-floricultores.html"
    },
    {
      "id": 21283,
      "tipo": "Notícia",
      "titulo": "Tradição e modernidade no cafezinho do dia a dia",
      "introducao": "Num dos restaurantes mais antigos do centro do Rio de Janeiro, os garçons – alguns com mais de 20 anos de casa e conhecidos pelo nome – retiram os pratos e talheres após o almoço. Lá, ainda é possível pedir como manda a tradição: “um cafezinho e a conta,...",
      "data_publicacao": "24/05/2018 02:00:32",
      "produto_id": 15784,
      "produtos": "15784|A Geografia do Café|a-geografia-do-cafe|2261",
      "editorias": "revistaretratos",
      "imagens": "{\"image_intro\":\"images\\/agenciadenoticias\\/revista_retratos\\/Revista11\\/cafe_thumb.jpg\",\"float_intro\":\"\",\"image_intro_alt\":\"\",\"image_intro_caption\":\"\",\"image_fulltext\":\"images\\/agenciadenoticias\\/revista_retratos\\/Revista11\\/cafe_home.jpg\",\"float_fulltext\":\"\",\"image_fulltext_alt\":\"\",\"image_fulltext_caption\":\"\"}",
      "produtos_relacionados": "15784",
      "destaque": true,
      "link": "http://agenciadenoticias.ibge.gov.br/agencia-noticias/2012-agencia-de-noticias/noticias/21283-tradicao-e-modernidade-no-cafezinho-do-dia-a-dia.html"
    }
  ]
}

export const favoriteNews = [
    {
        "id": 40549,
        "titulo": "Produção industrial recua 0,9% em maio, segundo mês seguido de queda",
        "link": "http://agenciadenoticias.ibge.gov.br/agencia-noticias/2012-agencia-de-noticias/noticias/40549-producao-industrial-recua-0-9-em-maio-segundo-mes-seguido-de-queda.html",
        "imagens": "{\"image_intro\":\"images\\/agenciadenoticias\\/estatisticas_economicas\\/2024_07\\/PIM-Br_THUMBE-Roberto-DziuraJr-AEN.jpg\",\"float_intro\":\"\",\"image_intro_alt\":\"\",\"image_intro_caption\":\"\",\"image_fulltext\":\"images\\/agenciadenoticias\\/estatisticas_economicas\\/2024_07\\/PIM-Br_HOME-Roberto-DziuraJr-AEN.jpg\",\"float_fulltext\":\"\",\"image_fulltext_alt\":\"\",\"image_fulltext_caption\":\"\"}",
        "tipo": "Notícia",
        "data_publicacao": "03/07/2024 09:00:00"
    },
    {
        "id": 40548,
        "titulo": "Produção industrial recua 0,9% em maio",
        "link": "http://agenciadenoticias.ibge.gov.br/agencia-sala-de-imprensa/2013-agencia-de-noticias/releases/40548-producao-industrial-recua-0-9-em-maio.html",
        "imagens": "{\"image_intro\":\"images\\/agenciadenoticias\\/releases\\/PIM-PF-BR_Release1.png\",\"float_intro\":\"\",\"image_intro_alt\":\"\",\"image_intro_caption\":\"\",\"image_fulltext\":\"images\\/agenciadenoticias\\/releases\\/PIM-PF-BR_Release1.png\",\"float_fulltext\":\"\",\"image_fulltext_alt\":\"\",\"image_fulltext_caption\":\"\"}",
        "tipo": "Release",
        "data_publicacao": "03/07/2024 09:00:00"
    },
    {
        "id": 40569,
        "titulo": "IBGE assina protocolo de intenções com Ministério da Previdência Social",
        "link": "http://agenciadenoticias.ibge.gov.br/agencia-noticias/2012-agencia-de-noticias/noticias/40569-ibge-assina-protocolo-de-intencoes-com-ministerio-da-previdencia-social.html",
        "imagens": "{\"image_intro\":\"images\\/agenciadenoticias\\/ibge\\/2024_07\\/IBGE_CarlosLuoi_THUMB.jpg\",\"float_intro\":\"\",\"image_intro_alt\":\"\",\"image_intro_caption\":\"\",\"image_fulltext\":\"images\\/agenciadenoticias\\/ibge\\/2024_07\\/IBGE_CarlosLuoi_HOME.jpg\",\"float_fulltext\":\"\",\"image_fulltext_alt\":\"\",\"image_fulltext_caption\":\"\"}",
        "tipo": "Notícia",
        "data_publicacao": "02/07/2024 05:06:08"
    }
]
